Employee/Models/ManagerViewModel.cs
namespace Employee.Models
{
    public class ManagerViewModel
    {
        public List<HistoryViewModel> HistoryInfo { get; set; } = null!;
        public Array employees { get; set; } = null!;
        public Array days { get; set; } = null!;
    }
}

Employee/Controllers/ManagerController.cs
using Employee.Data;
using Employee.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Employee.Controllers
{
    public class ManagerController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;
		public ManagerController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
		{
			_userManager = userManager;
			_signInManager = signInManager;
		}
		public IActionResult Index()
        {
            List<HistoryViewModel> historyViewModels = new List<HistoryViewModel>();
            var month = DateTime.Now.ToString("MM");
            var year = DateTime.Now.ToString("yyyy");
            var time = month + "." + year;
            var authedUser = User.Identity.Name;
            var userData = _userManager.Users.Where(e => e.UserName == authedUser).FirstOrDefault();
            var historiesTemp = db.Histories.Where(e => e.Date.Contains(time) && e.DM == userData.DM).ToList();
            foreach (var history in historiesTemp)
            {
                historyViewModels.Add(new HistoryViewModel()
                {
                    Id = history.Id,
                    Date = history.Date,
                    Employee = history.Employee,
                    DM = history.DM,
                    State = history.State
                });
            }
            var data = db.Employees.Where(e => e.DM == userData.DM).ToArray();
            string[] employees = new string[data.Length];
            var i = 0;
            foreach (var e in data)
            {
                employees[i] = e.Name;
                i++;
            }
            int[] months = new int[13] { 0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 };
            var checkYear = DateTime.Now.Year;
            if (checkYear % 4 == 0 && (checkYear % 100 != 0 || checkYear % 400 == 0))
            {
                months[2] = 29;
            }
            string[] days = new string[months[Convert.ToInt32(month)]];
            var day = "";
            for (var j = 1; j <= days.Length; j++)
            {
                if (j < 10)
                {
                    day = "0" + j + "." + month + "." + year;
                }
                else
                {
                    day = j + "." + month + "." + year;
                }
                days[j - 1] = day;
            }

            ManagerViewModel model = new ManagerViewModel();
            model.HistoryInfo = historyViewModels;
            model.employees = employees;
            model.days = days;
            return View(model);
        }
        [HttpPost]
        public void CreateHistory(History model)
        {
			var authedUser = User.Identity.Name;
			var userData = _userManager.Users.Where(e => e.UserName == authedUser).FirstOrDefault();
			History history = new History();
            history.Date = model.Date;
            history.Employee = model.Employee;
            history.DM = userData.DM;
            history.State = model.State;
            db.Histories.Add(history);
            db.SaveChanges();
        }
    }
}

Employee/Views/Shared/_Auth.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee</title>
    <link rel="stylesheet" href="~/css/auth.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employee.styles.css" asp-append-version="true" />
</head>
<lllbody>
    <header>
        <div class="page-container">
            <div class="navbar">
                <div class="logo-field">
                    <img class="logo" src="~/img/Apple.png" />
                </div>
            </div>
            <div class="auth-body">
                <div class="card">
                    @RenderBody()
                </div>
            </div>
        </div>
    </header>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</lllbody>
</html>

Employee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employee.styles.css" asp-append-version="true" />
</head>
<lllbody>
    <header>
        <div class="page-container">
            <div class="navbar">
                <div class="logo-field">
                    <img class="logo" src="~/img/apple.png" />
                </div>
                <a class="btn danger" href="@Url.Action("Logout", "Account")">Logout</a>
            </div>
            <div class="page-body">
                <div class="sidebar">
                    <a class="item" href="@Url.Action("Index", "Home")">Attendance Info</a>
                    <a class="item" href="@Url.Action("Department", "Home")">Depertments</a>
                    <a class="item" href="@Url.Action("DMManager", "Home")">DM Manager</a>
                    <a class="item" href="@Url.Action("Employee", "Home")">Employee</a>
                </div>
                <div class="panel">
                    @RenderBody()
                </div>
            </div>
            <div class="change-info-modal none" id="change_info_model">
                <div onclick="changeInfo('H')" class="H">Holiday</div>
                <div onclick="changeInfo('S')"  class="S">Sick</div>
                <div onclick="changeInfo('A')" class="A">Attendance</div>
            </div>
            <div onclick="hideModal()" class="background none" id="background"></div>
        </div>
    </header>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <script src="~/js/download.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        function changeInfo(state) {
            var line = sessionStorage.getItem("line");
            var number = sessionStorage.getItem("number");
            var _number = sessionStorage.getItem("_number");
            var _line = sessionStorage.getItem("_line");
            var id = sessionStorage.getItem("id");
            var date = sessionStorage.getItem("date");
            var employee = sessionStorage.getItem("employee");
            var info = sessionStorage.getItem("info");
            if(state == "A") {
                document.getElementById("infoTable").childNodes[_line].childNodes[_number].outerHTML = `<td b-myaos72j19 class='${state}' onmousedown="showInfoModal('${id}', '${date}', '${employee}', '${state}', '${line}', '${number}')"></td>`;
            } else {
                document.getElementById("infoTable").childNodes[_line].childNodes[_number].outerHTML = `<td b-myaos72j19 class='${state}' onmousedown="showInfoModal('${id}', '${date}', '${employee}', '${state}', '${line}', '${number}')">${state}</td>`;
            }
            document.getElementById("change_info_model").classList.replace("flex", "none");
            document.getElementById("background").classList.replace("flex", "none");
            g_state = false;
            UpdateHistory(id, date, employee, info, state);
        }
        function hideModal() {
            if (document.getElementById("background").classList.contains("flex")) {
                document.getElementById("background").classList.replace("flex", "none")
            }
            if (document.getElementById("change_info_model").classList.contains("flex")) {
                document.getElementById("change_info_model").classList.replace("flex", "none");
                g_state = false;
            }
            if (document.getElementById("department_model").classList.contains("flex")) {
                document.getElementById("department_model").classList.replace("flex", "none")
            }
            if (document.getElementById("manager_model").classList.contains("flex")) {
                document.getElementById("manager_model").classList.replace("flex", "none")
            }
            if (document.getElementById("employee_model").classList.contains("flex")) {
                document.getElementById("employee_model").classList.replace("flex", "none")
            }
        }
        function UpdateHistory(id, date, employee, info, state) {
            
            var dm = $("#department").val();
            var creatForm = new FormData();
            creatForm.append("date", date);
            creatForm.append("employee", employee);
            creatForm.append("dm", dm);
            creatForm.append("state", state);
            var updateForm = new FormData();
            updateForm.append("id", id);
            updateForm.append("state", state);
            var deleteForm = new FormData();
            deleteForm.append("id", id);

            if(info != state && info == "A") {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("CreateHistory", "Home")',
                    contentType: false,
                    processData: false,
                    cache: false,
                    data: creatForm,
                    success: function (response) {

                    }
                })
            } else if(state == "A"){
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("DeleteHistory", "Home")',
                    contentType: false,
                    processData: false,
                    cache: false,
                    data: deleteForm,
                    success: function (response) {

                    }
                })
            } else {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("UpdateHistory", "Home")',
                    contentType: false,
                    processData: false,
                    cache: false,
                    data: updateForm,
                    success: function (response) {

                    }
                })
            }
        }
    </script>
</lllbody>
</html>

Employee/Views/Shared/_Manager.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employee.styles.css" asp-append-version="true" />
</head>
<lllbody>
    <header>
        <div class="page-container">
            <div class="navbar">
                <div class="logo-field">
                    <img class="logo" src="~/img/apple.png" />
                </div>
                <a class="btn danger" href="@Url.Action("Logout", "Account")">Logout</a>
            </div>
            <div class="page-body">
                <div class="manager-panel">
                    @RenderBody()
                </div>
            </div>
            <div class="change-info-modal none" id="change_info_model">
                <div onclick="changeInfo('H')" class="H">Holiday</div>
                <div onclick="changeInfo('S')"  class="S">Sick</div>
                <div onclick="changeInfo('A')" class="A">Attendance</div>
            </div>
            <div onclick="hideModal()" class="background none" id="background"></div>
        </div>
    </header>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <script src="~/js/download.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        function changeInfo(state) {
            var line = sessionStorage.getItem("line");
            var number = sessionStorage.getItem("number");
            var _number = sessionStorage.getItem("_number");
            var _line = sessionStorage.getItem("_line");
            var id = sessionStorage.getItem("id");
            var date = sessionStorage.getItem("date");
            var employee = sessionStorage.getItem("employee");
            var info = sessionStorage.getItem("info");
            if(state == "A") {
                document.getElementById("infoTable").childNodes[_line].childNodes[_number].outerHTML = `<td b-myaos72j19 class='${state}' onmousedown="showInfoModal('${id}', '${date}', '${employee}', '${state}', '${line}', '${number}')"></td>`;
            } else {
                document.getElementById("infoTable").childNodes[_line].childNodes[_number].outerHTML = `<td b-myaos72j19 class='${state}' onmousedown="showInfoModal('${id}', '${date}', '${employee}', '${state}', '${line}', '${number}')">${state}</td>`;
            }
            document.getElementById("change_info_model").classList.replace("flex", "none");
            document.getElementById("background").classList.replace("flex", "none");
            g_state = false;
            UpdateHistory(id, date, employee, info, state);
        }
        function hideModal() {
            if (document.getElementById("background").classList.contains("flex")) {
                document.getElementById("background").classList.replace("flex", "none")
            }
            if (document.getElementById("change_info_model").classList.contains("flex")) {
                document.getElementById("change_info_model").classList.replace("flex", "none");
                g_state = false;
            }
            if (document.getElementById("department_model").classList.contains("flex")) {
                document.getElementById("department_model").classList.replace("flex", "none")
            }
            if (document.getElementById("manager_model").classList.contains("flex")) {
                document.getElementById("manager_model").classList.replace("flex", "none")
            }
            if (document.getElementById("employee_model").classList.contains("flex")) {
                document.getElementById("employee_model").classList.replace("flex", "none")
            }
        }
        function UpdateHistory(id, date, employee, info, state) {
            
            var creatForm = new FormData();
            creatForm.append("date", date);
            creatForm.append("employee", employee);
            creatForm.append("state", state);
            var updateForm = new FormData();
            updateForm.append("id", id);
            updateForm.append("state", state);
            var deleteForm = new FormData();
            deleteForm.append("id", id);

            if(info != state && info == "A") {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("CreateHistory", "Manager")',
                    contentType: false,
                    processData: false,
                    cache: false,
                    data: creatForm,
                    success: function (response) {

                    }
                })
            } else if(state == "A"){
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("DeleteHistory", "Home")',
                    contentType: false,
                    processData: false,
                    cache: false,
                    data: deleteForm,
                    success: function (response) {

                    }
                })
            } else {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("UpdateHistory", "Home")',
                    contentType: false,
                    processData: false,
                    cache: false,
                    data: updateForm,
                    success: function (response) {

                    }
                })
            }
        }
    </script>
</lllbody>
</html>